/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.Collections;
import java.util.List;

public class PrimeFactors {
    public boolean someLibraryMethod() {
        return true;
    }


    public List checkFactors(int Number) {
        if(Number == 1){
            return Collections.emptyList();
        }
        else if(Number == 2){
            return List.of(2);
        }
        return null;
    }
}
